package com.revenuecat.purchases.utils;

import Lc.l;
import android.os.Parcel;
import id.AbstractC3557B;
import kotlin.Metadata;
import org.json.JSONObject;

@Metadata(d1 = {"\u0000\"\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0005\b\u00c0\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002\u00a2\u0006\u0004\b\f\u0010\rJ\u0017\u0010\u0005\u001a\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u0003H\u0016\u00a2\u0006\u0004\b\u0005\u0010\u0006J#\u0010\n\u001a\u00020\t*\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\b\u001a\u00020\u0007H\u0016\u00a2\u0006\u0004\b\n\u0010\u000b\u00a8\u0006\u000e"}, d2 = {"Lcom/revenuecat/purchases/utils/JSONObjectParceler;", "", "Lorg/json/JSONObject;", "Landroid/os/Parcel;", "parcel", "create", "(Landroid/os/Parcel;)Lorg/json/JSONObject;", "", "flags", "Ljf/y;", "write", "(Lorg/json/JSONObject;Landroid/os/Parcel;I)V", "<init>", "()V", "purchases_customEntitlementComputationRelease"}, k = 1, mv = {1, 7, 1})
/* loaded from: classes.dex */
public final class JSONObjectParceler {
    public static final JSONObjectParceler INSTANCE = new JSONObjectParceler();

    private JSONObjectParceler() {
    }

    public JSONObject create(Parcel parcel) {
        AbstractC3557B.c0("parcel", parcel);
        return new JSONObject(parcel.readString());
    }

    public JSONObject[] newArray(int i10) {
        throw new l("Generated by Android Extensions automatically", 1);
    }

    public void write(JSONObject jSONObject, Parcel parcel, int i10) {
        AbstractC3557B.c0("<this>", jSONObject);
        AbstractC3557B.c0("parcel", parcel);
        parcel.writeString(jSONObject.toString());
    }
}
